server:
  port: 8888
  servlet:
    context-path: /aa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

#配置 mybatis-config.xml 路径，mybatis-config.xml 中配置 MyBatis 基础属性
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.kk
#  #配置sql的打印 //包路径为mapper文件包路径
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
